name: CI
on:
  push:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: archlinux
      options: --privileged --device /dev/fuse
      volumes:
        - ${{ github.workspace }}:/home/ci/github
        - /tmp:/tmp
    steps:
      - name: Install packages
        run: pacman -Suy --noconfirm rsync docker git

      - name: Git safe working-directory
        run: git config --global --add safe.directory /home/ci/github

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Set up .env
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" | base64 -d > .env
        working-directory: /home/ci/github

      - name: Run
        run: ./build.sh
        working-directory: /home/ci/github
